avatar/urls.py
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

geodb/urls.py
from tastypie.api import Api
from .geoapi import FloodRiskStatisticResource, getProvince, EarthQuakeStatisticResource, getEQEvents, getAccessibilities, getSAMParameters, getIncidentsRaw, getVillages, getLastUpdatedStatus, getLandslide, getDrought, getClosestDroughtWOYLayerAPI

geoapi = Api(api_name='geoapi')

geoapi.register(FloodRiskStatisticResource())
geoapi.register(getProvince())
geoapi.register(EarthQuakeStatisticResource())
geoapi.register(getEQEvents())
geoapi.register(getAccessibilities())
geoapi.register(getSAMParameters())
geoapi.register(getIncidentsRaw())
geoapi.register(getVillages())
geoapi.register(getLastUpdatedStatus())
geoapi.register(getLandslide())
geoapi.register(getDrought())
geoapi.register(getClosestDroughtWOYLayerAPI())

geonode/layers/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.conf import settings
from django.views.generic import TemplateView

js_info_dict = {
    'packages': ('geonode.layers',),
}

urlpatterns = patterns(
    'geonode.layers.views',
    url(r'^$', TemplateView.as_view(template_name='layers/layer_list.html'), name='layer_browse'),
    # ubah
    # url(r'^v2/$', TemplateView.as_view(template_name='v2/layer_list.html'), name='layer_browse', namespace='v2'),
    # /ubah
    url(r'^upload$', 'layer_upload', name='layer_upload'),
    url(r'^(?P<layername>[^/]*)$', 'layer_detail', name="layer_detail"),
    url(r'^(?P<layername>[^/]*)/metadata$', 'layer_metadata', name="layer_metadata"),
    url(r'^(?P<layername>[^/]*)/remove$', 'layer_remove', name="layer_remove"),
    url(r'^(?P<layername>[^/]*)/replace$', 'layer_replace', name="layer_replace"),
    url(r'^(?P<layername>[^/]*)/thumbnail$', 'layer_thumbnail', name='layer_thumbnail'),

    # url(r'^api/batch_permissions/?$', 'batch_permissions',
    #    name='batch_permssions'),
    # url(r'^api/batch_delete/?$', 'batch_delete', name='batch_delete'),
)

# -- Deprecated url routes for Geoserver authentication -- remove after GeoNode 2.1
# -- Use /gs/acls, gs/resolve_user/, gs/download instead
if 'geonode.geoserver' in settings.INSTALLED_APPS:
    urlpatterns = patterns('geonode.geoserver.views',
                           url(r'^acls/?$', 'layer_acls', name='layer_acls_dep'),
                           url(r'^resolve_user/?$', 'resolve_user', name='layer_resolve_user_dep'),
                           url(r'^download$', 'layer_batch_download', name='layer_batch_download_dep'),
                           ) + urlpatterns

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls

from geonode.api.urls import api
from geodb.urls import geoapi

import autocomplete_light
import dashboard
import securitydb
import pushnotif
import deliverynotes

from geonode.documents.urls_api_checkpdf import api as api_checkpdf

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

v2urlpatterns = patterns('',

                       url(r'^/?$', TemplateView.as_view(template_name='v2/index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='v2/help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='v2/developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='v2/about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='v2/disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='v2/partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='v2/video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='v2/training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='v2/doc.html'), name='documentation'),

                       url(r'^layers/$', TemplateView.as_view(template_name='v2/layer_list.html'), name='layer_browse'),
                       url(r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='map_browse'),
                       url(r'^documents/$', TemplateView.as_view(template_name='v2/document_list.html'), name='document_browse'),

                       (r'^layers/', include('geonode.layers.urls')),

                       (r'^maps/', include('geonode.maps.urls')),
                       # (r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='v2_maps_browse'),

                       url(r'^search/$', TemplateView.as_view(template_name='search/v2/search.html'), name='search'),

                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),

                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^/', include('dashboard.urls')),
                       (r'^dashboard/', include('dashboard.urls')),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^people/', include('geonode.people.urls')),
                       (r"^covid19/", include("covid19.urls")),
                       )

urlpatterns = patterns('',
                      # change server into v2
                       (r'^', include(v2urlpatterns, namespace='v2')),

                       # Static pages
                       url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='documentation.html'), name='documentation'),

                       # Publication Web
                       url(r'^publication/flooding/$', TemplateView.as_view(template_name='publication/flooding/Look8.html'), name='flooding_publication'),
                       url(r'^publication/avalanches/$', TemplateView.as_view(template_name='publication/avalanches/index.html'), name='avalanche_publication'),
                       url(r'^publication/earthquake/$', TemplateView.as_view(template_name='publication/earthquake/index.html'), name='earthquake_publication'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),

                       # Users statistics
                       url(r'^userstatistics$', 'userstatistics.views.userstatistics', name='userstatistics'),

                      (r'^deliverynotes/', include('deliverynotes.urls')),

                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^dashboard/', include('dashboard.urls')),

                       (r'^securitydb/', include('securitydb.urls')),

                       # v2 will overwrite named url with the same name
                       (r'^v2/', include(v2urlpatterns, namespace='v2')),

                       (r'^pushnotif/', include('pushnotif.urls')),
                       url(r'', include('geonode.documents.urls_api_checkpdf'))
                       
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/layers/templates/layers/layer_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}data{% endblock %}

{% block body_outer %}
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/layers/templates/layers/layer_list.html
{% extends "layers/layer_base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Explore Layers" %} - {{ block.super }} {% endblock %}

{% block body_class %}layers explore{% endblock %}

{% block body %}
<section class="social">
  <div class="container forceCenter panel-header-custom">
      <a style="margin: 3px;" href="{% url "layer_upload" %}" class="btn btn-primary pull-right">{% trans "Upload Layers" %}</a>
      <div class="each-page-title">{% trans "Layers" %} <span ng-bind="total_counts" class="badge"></span></div>
      {% include "search/_sort_filters.html" %}
  </div>
</section> 
  {% with include_type_filter='true' %}
  {% with facet_type='layers' %}
  {% with header='Type' %}
  {% with filter='type__in' %}
  {% include "search/_search_content.html" %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% with is_layer='true' %}
  {% include "_bulk_permissions_form.html" %}
  {% endwith %}
{% endblock %}

{% block extra_script %}
  {% if GEONODE_SECURITY_ENABLED %}
    {% include "_permissions_form_js.html" %}
  {% endif %}
  <script type="text/javascript">
      {% if HAYSTACK_SEARCH %}
          SEARCH_URL = '{% url 'api_get_search' api_name='api' resource_name='base' %}?type__in=layer'
      {% else %}
          SEARCH_URL = '{% url 'api_dispatch_list' api_name='api' resource_name='layers' %}';
      {% endif %}
    FILTER_TYPE = 'layer';
  </script>
  {% with include_spatial='true' %}
  {% include 'search/search_scripts.html' %}
  {% endwith %}
{% endblock extra_script %}

geonode/layers/templates/layers/layer_style_manage.html
{% extends "v2/layer_base.html" %}
{% load i18n %}

{% block title %}{{ layer.typename }} — {{ block.super }}{% endblock %}

{% block body_class %}layers{% endblock %}

{% block body_outer %}
    <!-- Title -->
    <section class="title">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>{% trans "Manage Styles" %}</h1>
                </div>
                <div class="col-md-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="{% url 'v2:layer_browse' %}">{% trans "Layers" %}</a></li> 
                        <li><a href="{{ layer.get_absolute_url }}">{{ layer.title }}</a></li> 
                        <li class="active">{% trans "Manage Styles" %}</li>
                    </ul>
                </div>
            </div>
        </div>
      </section>
  
      <section>
          <div class="container">
                {% if error %}
                    <div class="alert alert-error">{{ error }}</div>
                {% endif %}

                <h4>{% blocktrans with layer.typename as layer_title %}
                    Manage Available Styles for <a href="/layers/{{ layer_title }}">{{ layer_title }}</a>
                    {% endblocktrans %}</h4>
                <form action="{% url "layer_style_manage" layer.service_typename %}" method="POST">
                    <div class="row grid-spacer">
                        <fieldset>
                            <div class="col-md-3">
                                <h4>{% trans "Layer Default Style" %}</h4>
                            </div>
                            <div class="col-md-6">
                                <select id='default_style' name='default_style' required='required'>
                                    {% for style in layer_styles %}
                                    {% if style = layer.default_style %}
                                    <option value="{{ style.0 }}" selected>{{ style.1 }}</option>
                                    {% else %}
                                    <option value="{{ style.0 }}">{{ style.1 }}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </fieldset>
                    </div>
                    <div class="row grid-spacer">
                        <fieldset>
                            <div class="col-md-3">
                                <h4>{% trans "Available styles" %}</h4>
                                <p>{% trans "Click on an available style in the upper box to assign it to this layer. Selected styles appear in the lower box." %}
                                </p>
                            </div>
                            <div class="col-md-9">
                                <select multiple="multiple" id="style-select" name="style-select">
                                    {% for style in gs_styles %}
                                    {% if style in layer_styles %}
                                    <option value='{{ style.0 }}' selected>{{ style.1 }}</option>
                                    {% else %}
                                    <option value='{{ style.0 }}'>{{ style.1 }}</option>
                                    {% endif %}
                                    {% endfor %}
                                </select>
                                {% csrf_token %}
                                <input type="hidden" value="{{ layer.service_typename }}" />
                            </div>
                        </fieldset>
                    </div>
                    <div class="row grid-spacer">
                        <div class="col-md-offset-3 col-md-6 form-actions">
                            <input type="submit" value="{% trans "Update Available Styles" %}" class="btn btn-danger" />
                        </div>
                    </div>
                </form>
          </div>
      </section>
{% endblock %}

{% block extra_script %}
    <script type="text/javascript">
        $(function () {

            $('#style-select').multiSelect({
                afterSelect: function (values) {
                    $('#default_style').append($("<option/>", {
                        value: values[0],
                        text: values[0]
                    }));
                },
                afterDeselect: function (values) {
                    $('#default_style option').each(function () {
                        if ($(this).val() == values[0]) {
                            $(this).remove();
                        }
                    });
                }
            });

        });
    </script>
{% endblock %}