avatar/urls.py
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

dashboard/urls.py
from . import views
from django.conf.urls import include, patterns, url

urlpatterns = patterns(
    'dashboard.views',
    url(r'^$', 'dashboard_detail', name='dashboard_detail'),
    url(r'^print$', 'dashboard_print', name='dashboard_print'),
    url(r'^multiple$', 'dashboard_multiple', name='dashboard_multiple'),
    url(r'^getprovinces$', 'get_provinces', name='get_provinces'),
    url(r'^classmarker$', 'classmarkerRedirect', name='classmarkerRedirect'),
    url(r'^classmarker_university$', 'classmarkerUnivesityRedirect', name='classmarkerUnivesityRedirect'),
    url(r'^classmarker_insert$', 'classmarkerInsert', name='classmarkerInsert'),
    url(r'^downloadPDFFile$', 'downloadPDFFile', name='downloadPDFFile'),
    
)

geodb/urls.py
from tastypie.api import Api
from .geoapi import FloodRiskStatisticResource, getProvince, EarthQuakeStatisticResource, getEQEvents, getAccessibilities, getSAMParameters, getIncidentsRaw, getVillages, getLastUpdatedStatus, getLandslide, getDrought, getClosestDroughtWOYLayerAPI

geoapi = Api(api_name='geoapi')

geoapi.register(FloodRiskStatisticResource())
geoapi.register(getProvince())
geoapi.register(EarthQuakeStatisticResource())
geoapi.register(getEQEvents())
geoapi.register(getAccessibilities())
geoapi.register(getSAMParameters())
geoapi.register(getIncidentsRaw())
geoapi.register(getVillages())
geoapi.register(getLastUpdatedStatus())
geoapi.register(getLandslide())
geoapi.register(getDrought())
geoapi.register(getClosestDroughtWOYLayerAPI())

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls

from geonode.api.urls import api
from geodb.urls import geoapi

import autocomplete_light
import dashboard
import securitydb
import pushnotif
import deliverynotes

from geonode.documents.urls_api_checkpdf import api as api_checkpdf

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

v2urlpatterns = patterns('',

                       url(r'^/?$', TemplateView.as_view(template_name='v2/index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='v2/help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='v2/developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='v2/about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='v2/disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='v2/partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='v2/video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='v2/training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='v2/doc.html'), name='documentation'),

                       url(r'^layers/$', TemplateView.as_view(template_name='v2/layer_list.html'), name='layer_browse'),
                       url(r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='map_browse'),
                       url(r'^documents/$', TemplateView.as_view(template_name='v2/document_list.html'), name='document_browse'),

                       (r'^layers/', include('geonode.layers.urls')),

                       (r'^maps/', include('geonode.maps.urls')),
                       # (r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='v2_maps_browse'),

                       url(r'^search/$', TemplateView.as_view(template_name='search/v2/search.html'), name='search'),

                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),

                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^/', include('dashboard.urls')),
                       (r'^dashboard/', include('dashboard.urls')),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^people/', include('geonode.people.urls')),
                       (r"^covid19/", include("covid19.urls")),
                       )

urlpatterns = patterns('',
                      # change server into v2
                       (r'^', include(v2urlpatterns, namespace='v2')),

                       # Static pages
                       url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='documentation.html'), name='documentation'),

                       # Publication Web
                       url(r'^publication/flooding/$', TemplateView.as_view(template_name='publication/flooding/Look8.html'), name='flooding_publication'),
                       url(r'^publication/avalanches/$', TemplateView.as_view(template_name='publication/avalanches/index.html'), name='avalanche_publication'),
                       url(r'^publication/earthquake/$', TemplateView.as_view(template_name='publication/earthquake/index.html'), name='earthquake_publication'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),

                       # Users statistics
                       url(r'^userstatistics$', 'userstatistics.views.userstatistics', name='userstatistics'),

                      (r'^deliverynotes/', include('deliverynotes.urls')),

                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^dashboard/', include('dashboard.urls')),

                       (r'^securitydb/', include('securitydb.urls')),

                       # v2 will overwrite named url with the same name
                       (r'^v2/', include(v2urlpatterns, namespace='v2')),

                       (r'^pushnotif/', include('pushnotif.urls')),
                       url(r'', include('geonode.documents.urls_api_checkpdf'))
                       
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

dashboard/models.py
from django.db import models

# Create your models here.
class classmarker(models.Model):
    cm_ts = models.FloatField(blank=True, null=True)
    cm_tsa= models.FloatField(blank=True, null=True)
    cm_tp = models.FloatField(blank=True, null=True)
    cm_td = models.CharField(max_length=50, blank=True)
    cm_fn = models.CharField(max_length=200, blank=True)
    cm_ln = models.CharField(max_length=200, blank=True)
    cm_e = models.CharField(max_length=100, blank=True)
    cm_user_id = models.CharField(max_length=50, blank=True)
    cm_access_list_item = models.CharField(max_length=255, blank=True)

dashboard/templates/v2/dash_ndisaster.html
{% load i18n %}
{% load humanize %}
{% load leaflet_tags %}

<section id="nd">
	<div class="container center frame-color embed-responsive embed-responsive-16by9">
		<iframe class="embed-responsive-item" frameborder="0" scrolling="no" src="https://public.tableau.com/views/Afghanistan-Natural-Disasters_0/Situation?:embed=y&:display_count=yes&:showTabs=y?:embed=yes&:tabs=no&:toolbar=yes&:showVizHome=no"></iframe>
	</div>
</section>

dashboard/templates/v2/dash_weather.html
{% load i18n %}
{% load humanize %}
{% load leaflet_tags %}

<section id="weather">
	<div class="container center frame-color embed-responsive embed-responsive-16by9">
		<iframe class="embed-responsive-item" frameborder="0" scrolling="no" src="https://www.ventusky.com/?p=35.3;68.8;5&l=temperature"></iframe>
	</div>
</section>

dashboard/templates/v2/links.html
{% load i18n %}

  <nav class="navbar navbar-lower" data-spy="affix" data-offset-top="70">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-lower-collapse">
          <i class="fa fa-chevron-down center"></i>
      </button>
      <div class="collapse navbar-collapse collapse-buttons navbar-lower-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'v2:dashboard_detail' %}?page=main{{add_link}}"><span>{% trans 'Overview' %}</span></a></li>
          <li><a href="{% url 'v2:dashboard_detail' %}?page=baseline{{add_link}}"><span>{% trans 'Baseline' %}</span></a></li>
          <li><a href="{% url 'v2:dashboard_detail' %}?page=accessibility{{add_link}}"><span>{% trans 'Accessibility' %}</span></a></li>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>{% trans 'Floods' %}</span>&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'v2:dashboard_detail' %}?page=floodforecast{{add_link}}">{% trans 'Flood Prediction' %}</a></li>
                <li><a href="{% url 'v2:dashboard_detail' %}?page=floodrisk{{add_link}}">{% trans 'Flood Risk' %}</a></li>
              </ul>

          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>{% trans 'Avalanches' %}</span>&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'v2:dashboard_detail' %}?page=avalcheforecast{{add_link}}">{% trans 'Avalanche Prediction' %}</a></li>
              <li><a href="{% url 'v2:dashboard_detail' %}?page=avalancherisk{{add_link}}">{% trans 'Avalanche Risk' %}</a></li>
            </ul>
          </li>
          <li>
              <a href="{% url 'v2:dashboard_detail' %}?page=landslide{{add_link}}"><span>{% trans 'Landslide' %}</span></a>
          </li>
          <li>
              <a href="{% url 'v2:dashboard_detail' %}?page=drought{{add_link}}"><span>{% trans 'Drought' %}</span></a>
          </li>
          <li>
              <a href="{% url 'v2:dashboard_detail' %}?page=earthquake{{add_link}}"><span>{% trans 'Earthquake' %}</span></a>
          </li>
          <li>
              <a href="{% url 'v2:dashboard_detail' %}?page=security{{add_link}}"><span>{% trans 'Humanitarian Access' %}</span></a>
          </li>
          <li>
              <a href="{% url 'v2:dashboard_detail' %}?page=naturaldisaster{{add_link}}"><span>{% trans 'Natural Disaster' %}</span></a>
          </li>
          <li>
            <a href="{% url 'v2:dashboard_detail' %}?page=weather{{add_link}}"><span>{% trans 'Weather' %}</span></a>
          </li>
          <li>
            <button id="pdf" class="btn btn-red" title="Download PDF"><i class="fa fa-file-pdf-o"></i></button>
          </li>
          <li class="pull-right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search" aria-hidden="true"></i></a>
            <ul class="dropdown-menu dropdown-search">
              <li>
                <var id="result-container" class="result-container"></var>
                <form id="form-country_v2" name="form-country_v2">
                  <div class="typeahead__container container-search">
                    <div class="typeahead__field">
                      <span class="typeahead__query search-query">
                        <input class="js-typeahead-country_v2 search" type="search" name="country_v2[query]" placeholder="{% trans 'Search' %}" autocomplete="off">
                      </span>
                      <span class="typeahead__button search-icon">
                        <button type="submit"><i class="fa fa-search"></i></button>
                      </span>
                    </div>
                  </div>
                </form>
              </li>
            </ul>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  {% include "v2/qlink_list.html" %}

  <script type="text/javascript">

    var _checked = [];

    function removeA(arr) {
        var what, a = arguments, L = a.length, ax;
        while (L > 1 && arr.length) {
            what = a[--L];
            while ((ax= arr.indexOf(what)) !== -1) {
                arr.splice(ax, 1);
            }
        }
        return arr;
    }

    document.addEventListener('DOMContentLoaded', function() {
      $.typeahead({
          input: '.js-typeahead-country_v2',
          minLength: 1,
          maxItem: 20,
          order: "asc",
          mustSelectItem : true,
          // href: "https://en.wikipedia.org/?title={{display}}",
          // template: "{{name}} <small style='color:#999;'>{{group}}</small>",
          template :function (query, item) {
            var url = $(location).attr("href");
            if (getParameterByName("code") == null){
              url += '&code='+item.code;
            } else {
              url = updateUrlParameter(url, 'code', item.code);
            }

            if (item.code == 0){
              url = removeParam('code', url)
            }

            item.href = url;
            if (item.group =='district'){
              return '<span class="row">' +
                  '<span>'+item.name+' <small style="color:#999;">'+item.group+' in '+item.parent+' province</small></span>' +
              "</span>";
            } else {
              return '<span class="row">' +
                  '<span>'+item.name+' <small style="color:#999;">'+item.group+'</small></span>' +
              "</span>";
            }
          },
          source: {
              country: {
                  display: "name",
                  href: "https://www.github.com/",
                  data: [{
                    "name":"Afghanistan",
                    "code":0
                  }]
              },
              province: {
                  display: "name",
                  href: "https://www.github.com/",
                  ajax: {
                      type: "GET",
                      url: "/dashboard/getprovinces",
                      path: "data.provinces"
                  }
              },
              district: {
                  display: "name",
                  href: "https://www.github.com/",
                  ajax: {
                      type: "GET",
                      url: "/dashboard/getprovinces",
                      path: "data.districts"
                  }
              }
          },
          callback: {
              onNavigateAfter: function (node, lis, a, item, query, event) {
                  if (~[38,40].indexOf(event.keyCode)) {
                      var resultList = node.closest("form").find("ul.typeahead__list"),
                          activeLi = lis.filter("li.active"),
                          offsetTop = activeLi[0] && activeLi[0].offsetTop - (resultList.height() / 2) || 0;

                      resultList.scrollTop(offsetTop);
                  }

              },
              onClickAfter: function (node, a, item, event) {

                  event.preventDefault();

                  // var r = confirm("You will be redirected to:\n" + item.href + "\n\nContinue?");
                  // if (r == true) {
                      // window.open(item.href);
                      window.document.location = item.href;
                  // }

                  $('#result-container').text('');

              },
              onResult: function (node, query, result, resultCount) {
                  if (query === "") return;

                  var text = "";
                  if (result.length > 0 && result.length < resultCount) {
                      text = "Showing <strong>" + result.length + "</strong> of <strong>" + resultCount + '</strong> elements matching "' + query + '"';
                  } else if (result.length > 0) {
                      text = 'Showing <strong>' + result.length + '</strong> elements matching "' + query + '"';
                  } else {
                      text = 'No results matching "' + query + '"';
                  }
                  $('#result-container').html(text);

              }//,
              // onMouseEnter: function (node, a, item, event) {

              //     if (item.group === "country") {
              //         $(a).append('<span class="flag-chart flag-' + item.display.replace(' ', '-').toLowerCase() + '"></span>')
              //     }

              // },
              // onMouseLeave: function (node, a, item, event) {

              //     $(a).find('.flag-chart').remove();

              // }
          }
      });


      $('button#pdf').on('click', function(event) {
        var url = $(location).attr("href");
        $(".se-pre-con").fadeIn("slow");
        window.document.location = url+'&pdf=true&_checked='+_checked;
        $(".se-pre-con").fadeOut("slow");
      });
    });
  </script>