avatar/urls.py
try:
    from django.conf.urls import url, patterns
except ImportError:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('avatar.views',
    url('^add/$', 'add', name='avatar_add'),
    url('^change/$', 'change', name='avatar_change'),
    url('^delete/$', 'delete', name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

geodb/urls.py
from tastypie.api import Api
from .geoapi import FloodRiskStatisticResource, getProvince, EarthQuakeStatisticResource, getEQEvents, getAccessibilities, getSAMParameters, getIncidentsRaw, getVillages, getLastUpdatedStatus, getLandslide, getDrought, getClosestDroughtWOYLayerAPI

geoapi = Api(api_name='geoapi')

geoapi.register(FloodRiskStatisticResource())
geoapi.register(getProvince())
geoapi.register(EarthQuakeStatisticResource())
geoapi.register(getEQEvents())
geoapi.register(getAccessibilities())
geoapi.register(getSAMParameters())
geoapi.register(getIncidentsRaw())
geoapi.register(getVillages())
geoapi.register(getLastUpdatedStatus())
geoapi.register(getLandslide())
geoapi.register(getDrought())
geoapi.register(getClosestDroughtWOYLayerAPI())

geonode/maps/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import patterns, url
from django.views.generic import TemplateView

js_info_dict = {
    'packages': ('geonode.maps',),
}

urlpatterns = patterns('geonode.maps.views',
                       url(r'^$', TemplateView.as_view(template_name='maps/map_list.html'), name='maps_browse'),
                       # ubah
                       # url(r'^v2/$', TemplateView.as_view(template_name='v2/map_list.html'), name='maps_browse'),
                       # /ubah
                       url(r'^new$', 'new_map', name="new_map"),
                       url(r'^new/data$', 'new_map_json', name='new_map_json'),
                       url(r'^checkurl/?$', 'ajax_url_lookup'),
                       url(r'^snapshot/create/?$', 'snapshot_create'),
                       url(r'^(?P<mapid>[^/]+)$', 'map_detail', name='map_detail'),
                       url(r'^(?P<mapid>[^/]+)/view$', 'map_view', name='map_view'),
                       url(r'^(?P<mapid>[^/]+)/data$', 'map_json', name='map_json'),
                       url(r'^(?P<mapid>[^/]+)/download$', 'map_download', name='map_download'),
                       url(r'^(?P<mapid>[^/]+)/wmc$', 'map_wmc', name='map_wmc'),
                       url(r'^(?P<mapid>[^/]+)/wms$', 'map_wms', name='map_wms'),
                       url(r'^(?P<mapid>[^/]+)/remove$', 'map_remove', name='map_remove'),
                       url(r'^(?P<mapid>[^/]+)/metadata$', 'map_metadata', name='map_metadata'),
                       url(r'^(?P<mapid>[^/]+)/embed$', 'map_embed', name='map_embed'),
                       url(r'^(?P<mapid>[^/]+)/history$', 'ajax_snapshot_history'),
                       url(r'^(?P<mapid>\d+)/thumbnail$', 'map_thumbnail', name='map_thumbnail'),
                       url(r'^(?P<mapid>[^/]+)/(?P<snapshot>[A-Za-z0-9_\-]+)/view$', 'map_view'),
                       url(r'^(?P<mapid>[^/]+)/(?P<snapshot>[A-Za-z0-9_\-]+)/info$', 'map_detail'),
                       url(r'^(?P<mapid>[^/]+)/(?P<snapshot>[A-Za-z0-9_\-]+)/embed/?$', 'map_embed'),
                       url(r'^(?P<mapid>[^/]+)/(?P<snapshot>[A-Za-z0-9_\-]+)/data$', 'map_json', name='map_json'),
                       url(r'^check/$', 'map_download_check', name='map_download_check'),
                       url(r'^embed/$', 'map_embed', name='map_embed'),
                       url(r'^(?P<layername>[^/]*)/attributes', 'maplayer_attributes', name='maplayer_attributes'),
                       # url(r'^change-poc/(?P<ids>\w+)$', 'change_poc', name='maps_change_poc'),
                       )

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView
from django.contrib import admin

import geonode.proxy.urls

from geonode.api.urls import api
from geodb.urls import geoapi

import autocomplete_light
import dashboard
import securitydb
import pushnotif
import deliverynotes

from geonode.documents.urls_api_checkpdf import api as api_checkpdf

# Setup Django Admin
autocomplete_light.autodiscover()

admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

v2urlpatterns = patterns('',

                       url(r'^/?$', TemplateView.as_view(template_name='v2/index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='v2/help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='v2/developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='v2/about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='v2/disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='v2/partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='v2/video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='v2/training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='v2/doc.html'), name='documentation'),

                       url(r'^layers/$', TemplateView.as_view(template_name='v2/layer_list.html'), name='layer_browse'),
                       url(r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='map_browse'),
                       url(r'^documents/$', TemplateView.as_view(template_name='v2/document_list.html'), name='document_browse'),

                       (r'^layers/', include('geonode.layers.urls')),

                       (r'^maps/', include('geonode.maps.urls')),
                       # (r'^maps/$', TemplateView.as_view(template_name='v2/map_list.html'), name='v2_maps_browse'),

                       url(r'^search/$', TemplateView.as_view(template_name='search/v2/search.html'), name='search'),

                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),

                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^/', include('dashboard.urls')),
                       (r'^dashboard/', include('dashboard.urls')),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^people/', include('geonode.people.urls')),
                       (r"^covid19/", include("covid19.urls")),
                       )

urlpatterns = patterns('',
                      # change server into v2
                       (r'^', include(v2urlpatterns, namespace='v2')),

                       # Static pages
                       url(r'^/?$', TemplateView.as_view(template_name='index.html'), name='home'),
                       url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
                       url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
                       url(r'^disclaimer/$', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
                       url(r'^partners/$', TemplateView.as_view(template_name='partners.html'), name='partners'),
                       url(r'^video/$', TemplateView.as_view(template_name='video.html'), name='video'),
                       url(r'^training/$', TemplateView.as_view(template_name='training.html'), name='training'),
                       url(r'^documentation/$', TemplateView.as_view(template_name='documentation.html'), name='documentation'),

                       # Publication Web
                       url(r'^publication/flooding/$', TemplateView.as_view(template_name='publication/flooding/Look8.html'), name='flooding_publication'),
                       url(r'^publication/avalanches/$', TemplateView.as_view(template_name='publication/avalanches/index.html'), name='avalanche_publication'),
                       url(r'^publication/earthquake/$', TemplateView.as_view(template_name='publication/earthquake/index.html'), name='earthquake_publication'),

                       # Layer views
                       (r'^layers/', include('geonode.layers.urls')),

                       # Map views
                       (r'^maps/', include('geonode.maps.urls')),

                       # Catalogue views
                       (r'^catalogue/', include('geonode.catalogue.urls')),

                       # Search views
                       url(r'^search/$', TemplateView.as_view(template_name='search/search.html'), name='search'),

                       # Social views
                       (r"^account/", include("account.urls")),
                       (r'^people/', include('geonode.people.urls')),
                       (r'^avatar/', include('avatar.urls')),
                       (r'^comments/', include('dialogos.urls')),
                       (r'^ratings/', include('agon_ratings.urls')),
                       (r'^activity/', include('actstream.urls')),
                       (r'^announcements/', include('announcements.urls')),
                       (r'^messages/', include('user_messages.urls')),
                       (r'^social/', include('geonode.social.urls')),
                       (r'^security/', include('geonode.security.urls')),

                       # Users statistics
                       url(r'^userstatistics$', 'userstatistics.views.userstatistics', name='userstatistics'),

                      (r'^deliverynotes/', include('deliverynotes.urls')),

                       # Accounts
                       url(r'^account/ajax_login$', 'geonode.views.ajax_login', name='account_ajax_login'),
                       url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup', name='account_ajax_lookup'),

                       # Meta
                       url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'),
                           name='lang'),

                       url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, name='jscat'),
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps},
                           name='sitemap'),

                       (r'^i18n/', include('django.conf.urls.i18n')),
                       (r'^autocomplete/', include('autocomplete_light.urls')),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^groups/', include('geonode.groups.urls')),
                       (r'^documents/', include('geonode.documents.urls')),

                       (r'^services/', include('geonode.services.urls')),
                       url(r'', include(api.urls)),
                       url(r'', include(geoapi.urls)),
                       (r'^getOverviewMaps/', include('geodb.custom_urls')),
                       (r'^dashboard/', include('dashboard.urls')),

                       (r'^securitydb/', include('securitydb.urls')),

                       # v2 will overwrite named url with the same name
                       (r'^v2/', include(v2urlpatterns, namespace='v2')),

                       (r'^pushnotif/', include('pushnotif.urls')),
                       url(r'', include('geonode.documents.urls_api_checkpdf'))
                       
                       )

if "geonode.contrib.dynamic" in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^dynamic/', include('geonode.contrib.dynamic.urls')),
                            )

if 'geonode.geoserver' in settings.INSTALLED_APPS:
    # GeoServer Helper Views
    urlpatterns += patterns('',
                            # Upload views
                            (r'^upload/', include('geonode.upload.urls')),
                            (r'^gs/', include('geonode.geoserver.urls')),
                            )

if 'notification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            (r'^notifications/', include('notification.urls')),
                            )

# Set up proxy
urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/maps/forms.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import autocomplete_light

from geonode.maps.models import Map
from geonode.base.forms import ResourceBaseForm


class MapForm(ResourceBaseForm):

    class Meta(ResourceBaseForm.Meta):
        model = Map
        exclude = ResourceBaseForm.Meta.exclude + (
            'zoom',
            'projection',
            'center_x',
            'center_y',
        )
        widgets = autocomplete_light.get_widgets_dict(Map)

geonode/maps/templates/v2/map_base.html
{% extends "v2/site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% block title_sub %}{% trans "Explore Maps" %}{% endblock %} - {{ block.super }} {% endblock %}

{% block body_class %}maps{% endblock %}

{% block body_outer %}
  <!-- <div class="span12">
    <ul class="nav nav-tabs" id="subnav-tabs">
      <li><a href="{% url "maps_browse" %}" class="explore">{% trans 'Explore Maps' %}</a></li>
    </ul>
  </div> -->
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock %}

geonode/maps/templates/v2/map_download.html
{% extends "maps/map_base.html" %}
{% load i18n %}

{% block body %}
<div class="span12">
  <h3>{% trans "Download" %} {{map.title}}</h3>
  <p>
    {% blocktrans %}
      Here you can download all the layers of this map that
      are hosted on this GeoNode.
    {% endblocktrans %}
    <ul>
      {% for layer in downloadable_layers %} 
        <li>
          {% if layer.local %}
            {{ layer.local_link|safe }}
          {% else %}
            {{ layer }}
          {% endif %}
        </li>
      {% empty %}
      {% blocktrans %}
      <div class="alert alert-warning">Could not find downloadable layers for this map. You can go back to  
      {% endblocktrans %}<a href="{% url 'map_detail' map.id %}">{{map.title}}</a></div>
      {% endfor %} 
    </ul>
   
    {% if locked_layers %}
      {% blocktrans %}
        Additionally, the map contains these layers which will not be downloaded
        due to security restrictions:
      {% endblocktrans %}
      <ul>
        {% for layer in locked_layers %} 
          <li>{{ layer.layer_title }}</li>
        {% endfor %} 
      </ul>
    {% endif %}

	  {% if remote_layers %}
      {% blocktrans %}
        Finally, the map contains these layers which will not be downloaded
        because they are not available directly from this GeoNode:
      {% endblocktrans %}
      <ul>
        {% for layer in remote_layers %} 
          <li>{{ layer }}</li>
        {% endfor %} 
      </ul>
    {% endif %}

    {% if map_status %}
      <div class="alert alert-success span8" id="download">
          <div id="pb-status">{% trans 'Downloading' %}...</div>
          <div class="progress">
            <div id="pb" class="bar bar-success"></div>
          </div>
          <a class="btn" href="#" id="cancel">{%  trans 'Cancel' %}</a>
          <a class="btn" href="{% url 'map_download' map.id %}" style="display:none;" id="retry">{%  trans 'Retry' %}</a>
      </div>
    {% elif downloadable_layers|length > 0 %} 
      <form action="{% url 'map_download' map.id %}" method="POST">
        {% csrf_token %}
        <div class="form-actions">
          <input type="submit" class="btn btn-primary" value="{% trans "Start downloading this map" %}" /> 
        </div>
      </form>
    {% endif %} 
</div>
{% endblock %}
{% block extra_script %}
<script type="text/javascript">

  {% autoescape off %}

  {% if map_status %} 
      
  $(function(){

    "use strict";

    var processID;
    var checkStatus = setInterval(function (){

      $.ajax({
        type: "GET",
        url : "{% url 'map_download_check' %}"
      })
      .done(function(result){
        var response = $.parseJSON(result);
        processID = response.process.id;

        if (response.process.status === "FINISHED") {
          $('#cancel').hide();
          $("#pb-status").html("{% trans  "Download Complete" %}");
          location.href = "{{geoserver}}rest/process/batchDownload/download/" +  processID;
          clearInterval(checkStatus);
        }

        if (response.process.status === "FAILED") {
          $('#download').attr({class:'alert alert-error'});
          $('.progress').hide();
          $('#cancel').hide();
          $('#retry').show();
          $("#pb-status").html("{% trans  "Download Failed" %}");
          clearInterval(checkStatus);
        }

        $("#pb").css("width", response.process.progress + "%");
      });
    }, 1000);

    $("#cancel").click(function(){
      $.ajax({
        type: "GET",
        url: "{{geoserver}}rest/process/batchDownload/kill/" + processID
      })
      .done(function(){
        window.alert("You successfuly canceled the download"); 
        location.href = "{% url 'map_detail' map.id %}";
        clearInterval(checkStatus);
      })
      .fail(function(){
        clearInterval(checkStatus); // break if something fails
      });
    });
  });

  {% endif %}
  
  {% endautoescape %}

</script>
{% endblock extra_script %}

geonode/maps/templates/v2/map_embed.html
{% load i18n %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {% include "geonode/geo_header.html" %}
    <script type="text/javascript">
        google.load("earth", "1");
    </script>

    <script type="text/javascript">
    var app;
    Ext.onReady(function() {
    {% autoescape off %}
        var config = {
            useCapabilities: false,
            useToolbar: false,
            proxy: '{{ PROXY_URL }}',
            {% if MAPFISH_PRINT_ENABLED %}
            printService: "{{GEOSERVER_BASE_URL}}pdf/",
            {% else %}
            printService: "",
            {% endif %}
            /* The URL to a REST map configuration service.  This service 
             * provides listing and, with an authenticated user, saving of 
             * maps on the server for sharing and editing.
             */
            rest: "/maps/"
        };

        Ext.apply(config, {{ config }});
        app = new GeoExplorer.Viewer(config);

    {% endautoescape %}
    });
    </script>
{% endblock %}

{% block body %}
{% endblock %}

geonode/maps/templates/v2/map_include.html
{% include "geonode/ext_header.html" %}
{% include "geonode/app_header.html" %}
{% include "geonode/geo_header.html" %}
<script type="text/javascript">
var app;
Ext.onReady(function() {
{% autoescape off %}
    GeoExt.Lang.set("{{ LANGUAGE_CODE }}");
    var config = Ext.apply({
        tools: [{
            ptype: "gxp_wmsgetfeatureinfo",
            format: "grid",
            actionTarget: "main.tbar",
            outputConfig: {width: 400, height: 200, panIn: false}
        }],
        useToolbar: true,
        {% if PROXY_URL %}
        proxy: '{{ PROXY_URL }}',
        {% endif %}
        {% if MAPFISH_PRINT_ENABLED %}
        printService: "{{GEOSERVER_BASE_URL}}pdf/",
        {% else %}
        printService: "",
        {% endif %} 
        rest: "/maps/",

        // tell the map viewer where and how to be rendered
        portalConfig: {
            height: 400,
            renderTo: "the_map"
        }
    }, {{ config }});
app = new GeoExplorer.Viewer(config);
{% endautoescape %}
});
</script>

geonode/maps/templates/v2/map_metadata.html
{% extends "v2/map_base.html" %}
{% load i18n %}
{% load bootstrap_tags %}

{% block title %}{{ map.title }} — {{ block.super }}{% endblock %}

{% block body_class %}data{% endblock %}

{% block body_outer %}

    <!-- Title -->
    <section class="title">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>{% trans "Edit Metadata" %}</h1>
                </div>
                <div class="col-md-6">
                    <ul class="breadcrumb pull-right">
                        <li>{% trans 'Maps' %}</li>
                        <li><a href="{% url 'v2:maps_browse' %}">{% trans "Interactive Maps" %}</a></li> 
                        <li><a href="{{ map.get_absolute_url }}">{{ map.title }}</a></li> 
                        <li class="active">{% trans "Edit Metadata" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-push-2">
                    <div class="">
                        <p class="lead center">
                            {% blocktrans with map.title as map_title %}
                            Editing details for {{ map_title }}
                            {% endblocktrans %}
                        </p>
                        <form class="form-horizontal" action="{{ map.get_absolute_url }}/metadata" method="POST">
                            {% if map.metadata_uploaded %}
                            <div class="alert alert-warning" style="background-color: orange;">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>{% trans "Warning!" %}</strong> {% blocktrans %}Note: this map's orginal metadata was
                                populated by importing a metadata XML file.
                                GeoNode's metadata import supports a subset of ISO, FGDC, and Dublin Core metadata elements.
                                Some of your original metadata may have been lost.{% endblocktrans %}
                            </div>
                            {% endif %}
        
                            {% if map_form.errors or category_form.errors %}
                            <div class="alert alert-danger" style="background-color: pink">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>{% trans "Error!" %}</strong> {% blocktrans %}Error updating metadata. Please
                                check the following fields: {% endblocktrans %}
                                <ul>
                                    {% for field in map_form %}
                                    {% if field.errors %}
                                    <li>{{ field.label }}</li>
                                    {% endif %}
                                    {% endfor %}
        
                                    {% if category_form.errors %}
                                    <li>{{ category_form.errors.as_ul }}</li>
                                    {% endif %}
                                </ul>
                            </div>
                            {% endif %}
                            <div class="form-actions" style="margin:5px;text-align:right;">
                                <input type="submit" class="btn btn-primary" value="{% trans "Update" %}" />
                            </div>
                            {% csrf_token %}
                            <div class="form-controls">
                                {{ map_form|as_bootstrap }}
                            </div>
                            <fieldset class="form-controls modal-forms modal hide fade" id="poc_form">
                                <h2>{% trans "Point of Contact" %}</h2>
                                {{ poc_form|as_bootstrap }}
                                <button type='button' class="modal-cloose-btn btn btn-primary">Done</button>
                            </fieldset>
                            <fieldset class="form-controls modal-forms modal hide fade" id="metadata_form">
                                <h2>{% trans "Metadata Provider" %}</h2>
                                {{ author_form|as_bootstrap }}
                                <button type='button' class="modal-cloose-btn btn btn-primary">Done</button>
                            </fieldset>
                            <fieldset id="category_form">
                                <label class="control-label required-field">{% trans "Category" %}</label><br />
                                {% autoescape off %}
                                <div style="clear:both;padding-left:175px;">
                                    {% for choice in category_form.category_choice_field.field.choices %}
                                    <div style="width:50%;float:left;padding-bottom:5px;">
                                        <input type="radio" name="category_choice_field" value="{{ choice.0 }}"
                                            {% ifequal category_form.initial choice.0 %} checked="checked" {% endifequal %}>
                                        {{ choice.1 }}
                                        </input>
                                    </div>
                                    {% endfor %}
                                </div>
                                {% endautoescape %}
                            </fieldset>
                            <div class="form-actions" style="margin:5px;text-align:right;">
                                <input type="submit" class="btn btn-primary" value="{% trans "Update" %}" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block extra_script %}
    {% include 'metadata_form_js.html' %} 
{% endblock %}

geonode/maps/templates/v2/map_remove.html
{% extends "v2/map_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block title_sub %}{% trans "Deleting" %} {{ map.title }} {% endblock %}

{% block body_class %}maps{% endblock %}

{% block body_outer %}
    <!-- Title -->
    <section class="title">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>{% trans "Remove" %}</h1>
                </div>
                <div class="col-md-6">
                    <ul class="breadcrumb pull-right">
                        <li>{% trans 'Maps' %}</li>
                        <li><a href="{% url 'v2:maps_browse' %}">{% trans "Interactive Maps" %}</a></li> 
                        <li><a href="{{ map.get_absolute_url }}">{{ map.title }}</a></li> 
                        <li class="active">{% trans "Remove" %}</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="vertical-center">
                <div class="center">
                    <form action="{% url "map_remove" map.id %}" method="POST">
                        <p class="lead">
                            {% blocktrans with map.title as map_title %}
                            Are you sure you want to remove {{ map_title }}?
                            {% endblocktrans %}
                        </p>
                        {% csrf_token %}
                        <div class="form-actions">
                            <input type="submit" class="btn btn-danger" value="{% trans "Yes, I am sure"  %}" />
                            <a href="{{ map.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

geonode/maps/templates/v2/map_view.html
{% extends "v2/site_base.html" %}

{% load i18n %}

{% block title %} {% trans "GeoExplorer" %} - {{ block.super }} {% endblock %}

{% block head %}
{{ block.super }}
<style>
body {
  /* keep direction ltr for interactive maps*/
  direction: ltr;
}
</style>
{% include 'maps/map_geoexplorer.js' %}

{% endblock %}

{% block footer %}{% endblock %}